import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NexDock from "@/customs/dock";
import KeybindWrapper from "@/customs/keybind_wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative`}>
        <KeybindWrapper>{children}</KeybindWrapper>

        <div className="fixed bottom-8 w-full flex flex-row justify-center">
          <NexDock />
        </div>

        <div className="h-32" />
      </body>
    </html>
  );
}
